apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ include "hyperdx.namespace" . }}
  labels:
    {{- include "hyperdx.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
data:
  FRONTEND_URL: "{{ .Values.app.frontendUrl }}:{{ .Values.app.appPort }}"
  HYPERDX_API_PORT: "{{ .Values.app.apiPort }}"
  HYPERDX_APP_PORT: "{{ .Values.app.appPort }}"
  HYPERDX_APP_URL: {{ .Values.app.appUrl }}
  HYPERDX_LOG_LEVEL: {{ .Values.app.logLevel }}
  MINER_API_URL: "http://miner:5123"
  MONGO_URI: "mongodb://db:27017/hyperdx"
  SERVER_URL: "http://127.0.0.1:{{ .Values.app.apiPort }}"
  OPAMP_PORT: "{{ .Values.app.opampPort }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:{{ .Values.otelCollector.ports.otlpHttp }}"
  OTEL_SERVICE_NAME: "hdx-oss-app"
  USAGE_STATS_ENABLED: "true"
  DEFAULT_CONNECTIONS: |
    [{"name":"Local ClickHouse","host":"http://ch-server:{{ .Values.clickhouse.httpPort }}","username":"default","password":""}]
  DEFAULT_SOURCES: |
    [
      {"from":{"databaseName":"default","tableName":"otel_logs"},"kind":"log","timestampValueExpression":"TimestampTime","name":"Logs","displayedTimestampValueExpression":"Timestamp","implicitColumnExpression":"Body","serviceNameExpression":"ServiceName","bodyExpression":"Body","eventAttributesExpression":"LogAttributes","resourceAttributesExpression":"ResourceAttributes","defaultTableSelectExpression":"Timestamp,ServiceName,SeverityText,Body","severityTextExpression":"SeverityText","traceIdExpression":"TraceId","spanIdExpression":"SpanId","connection":"Local ClickHouse","traceSourceId":"Traces","sessionSourceId":"Sessions","metricSourceId":"Metrics"},
      {"from":{"databaseName":"default","tableName":"otel_traces"},"kind":"trace","timestampValueExpression":"Timestamp","name":"Traces","displayedTimestampValueExpression":"Timestamp","implicitColumnExpression":"SpanName","serviceNameExpression":"ServiceName","eventAttributesExpression":"SpanAttributes","resourceAttributesExpression":"ResourceAttributes","defaultTableSelectExpression":"Timestamp,ServiceName,StatusCode,round(Duration/1e6),SpanName","traceIdExpression":"TraceId","spanIdExpression":"SpanId","durationExpression":"Duration","durationPrecision":9,"parentSpanIdExpression":"ParentSpanId","spanNameExpression":"SpanName","spanKindExpression":"SpanKind","statusCodeExpression":"StatusCode","statusMessageExpression":"StatusMessage","connection":"Local ClickHouse","logSourceId":"Logs","sessionSourceId":"Sessions","metricSourceId":"Metrics"},
      {"from":{"databaseName":"default","tableName":""},"kind":"metric","timestampValueExpression":"TimeUnix","name":"Metrics","resourceAttributesExpression":"ResourceAttributes","metricTables":{"gauge":"otel_metrics_gauge","histogram":"otel_metrics_histogram","sum":"otel_metrics_sum"},"connection":"Local ClickHouse","logSourceId":"Logs","traceSourceId":"Traces","sessionSourceId":"Sessions"},
      {"from":{"databaseName":"default","tableName":"hyperdx_sessions"},"kind":"session","timestampValueExpression":"TimestampTime","name":"Sessions","displayedTimestampValueExpression":"Timestamp","implicitColumnExpression":"Body","serviceNameExpression":"ServiceName","bodyExpression":"Body","eventAttributesExpression":"LogAttributes","resourceAttributesExpression":"ResourceAttributes","defaultTableSelectExpression":"Timestamp,ServiceName,SeverityText,Body","severityTextExpression":"SeverityText","traceIdExpression":"TraceId","spanIdExpression":"SpanId","connection":"Local ClickHouse","logSourceId":"Logs","traceSourceId":"Traces","metricSourceId":"Metrics"}
    ]
