apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ch-data
  namespace: {{ include "hyperdx.namespace" . }}
  labels:
    {{- include "hyperdx.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.dataStorageSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ch-logs
  namespace: {{ include "hyperdx.namespace" . }}
  labels:
    {{- include "hyperdx.labels" . | nindent 4 }}
    app.kubernetes.io/component: clickhouse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.clickhouse.logsStorageSize }}
