apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: {{ include "hyperdx.namespace" . }}
  labels:
    {{- include "hyperdx.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  type: ClusterIP
  selector:
    {{- include "hyperdx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
  ports:
    - name: health
      port: {{ .Values.otelCollector.ports.health }}
      targetPort: {{ .Values.otelCollector.ports.health }}
    - name: fluentd
      port: {{ .Values.otelCollector.ports.fluentd }}
      targetPort: {{ .Values.otelCollector.ports.fluentd }}
    - name: otlp-grpc
      port: {{ .Values.otelCollector.ports.otlpGrpc }}
      targetPort: {{ .Values.otelCollector.ports.otlpGrpc }}
    - name: otlp-http
      port: {{ .Values.otelCollector.ports.otlpHttp }}
      targetPort: {{ .Values.otelCollector.ports.otlpHttp }}
    - name: metrics
      port: {{ .Values.otelCollector.ports.metrics }}
      targetPort: {{ .Values.otelCollector.ports.metrics }}
